definitions:
  script: &ssh_prepare mkdir -p ~/.ssh && echo $KNOWNHOSTS > ~/.ssh/known_hosts && (umask  077 ; echo $LAB19_STAGE_KEY_B64 | base64 --decode > ~/.ssh/id_rsa)
  steps: &steps
    - step:
        name: Set environment variables
        image: node:12.16.3
        script:
          - SITE_DIR="/var/www/$BITBUCKET_BRANCH-$BITBUCKET_REPO_SLUG"
          - echo "export SITE_DIR=\"$SITE_DIR\" ; " >> set_env.sh
        artifacts:
          - set_env.sh
    - parallel:
        - step:
            name: Yarn install
            image: node:12.16.3
            script:
              - source set_env.sh
              - yarn install
              - yarn run build
            caches:
              - node
            artifacts:
              - dist/**
        - step:
            name: Deploy using git
            script:
              - source set_env.sh
              - *ssh_prepare
              - >
                ssh lab19@$LAB19_STAGE_IP "echo \"Create site directory at $SITE_DIR \" ;
                mkdir -p $SITE_DIR ;

                echo \"Git pull from origin\" ;
                cd $SITE_DIR/ ;
                git init . ;
                git remote -v | grep "origin" || git remote add origin $BITBUCKET_GIT_SSH_ORIGIN ;
                git fetch origin;
                git reset --hard origin/$BITBUCKET_BRANCH ;

                echo \"Set directory group permissions\" ;
                sudo bash /var/opt/scripts/set-permissions.sh $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG ;

                composer install ;

                echo \"Completed deployment!\" ; "
    - step:
        name: Deploy artifacts
        script:
          - source set_env.sh
          - *ssh_prepare
          - scp -r dist lab19@$LAB19_STAGE_IP:$SITE_DIR

pipelines:
  branches:
    master: *steps
    develop: *steps
