name: Deploy to Staging

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Build
        run: STAGING_URL=https://${GITHUB_REF##*/}-${GITHUB_REPOSITORY#*/}.01.dvsb1.com yarn run stage
        env:
          NODE_ENV: production

      - name: Format
        run: yarn prettier --write "public/**/*.{js,json,md,scss,html}"

      - uses: actions/upload-artifact@v2
        with:
          name: dist-files
          path: public

      - name: Set up SSH
        run: |
          mkdir -pv ~/.ssh
          echo ${{ secrets.KNOWN_HOSTS }} > ~/.ssh/known_hosts
          (umask 077; echo ${{ secrets.DEPLOY_PRIVATE_KEY }} | base64 --decode > ~/.ssh/id_rsa)

      - name: Setup static file path
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "mkdir -p /var/www/${GITHUB_REF##*/}-${GITHUB_REPOSITORY#*/}"

      - name: Deploy dist files
        run: |
          scp -r public/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:/var/www/${GITHUB_REF##*/}-${GITHUB_REPOSITORY#*/}
